variables:
  TESTS_DIR: aws/tests

stages:
  - analysis
  - unittest


sonarqube:
  stage: analysis
  image: ${CI_REGISTRY}/ci-tools/sonar-scanner
  variables:
    SONAR_URL: https://sonar.iaas.checkpoint.com
    SONAR_ANALYSIS_MODE: publish
    SONAR_SOURCES: .
    SONAR_PROJECT_KEY: ${CI_PROJECT_NAME}-${GITLAB_USER_NAME}
    SONAR_TOKEN: ${CI_SONAR_TOKEN}
  script:
    - gitlab-sonar-scanner

terratest:
  stage: unittest
  image: ${CI_REGISTRY}/cloudguard-integrations/terratest:latest
  script:
    - go test -v -timeout 20m ${TESTS_DIR}/example_autoscale_test.go